{
 "title": "Crawler",
 "time": { "from": "2019-05-12T15:52:57.255Z", "to": "2019-05-12T17:03:17.036Z" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "95% процентиль на парсинг страницы",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(crawler_page_parse_time_bucket{kubernetes_namespace=~\"$namespace\"}[1m])) by (kubernetes_namespace,le))"
    }
   ]
  },
  {
   "title": "95% процентиль Время загрузки страницы",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(crawler_site_connection_time_bucket{kubernetes_namespace=~\"$namespace\"}[1m])) by (kubernetes_namespace,le))"
    }
   ]
  },
  {
   "title": "Динамика количества обработанных страниц\\сек",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_pages_parsed {kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  }
 ]
}